version: '3'
services:
  postgres:
    image: "postgres:14"
    container_name: "recipes-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=recipesdb
      - POSTGRES_USER=admin-user
      - POSTGRES_PASSWORD=admin-password
