CREATE TABLE users
(
    user_id            uuid,
    first_name         varchar not null,
    last_name          varchar not null,
    email_address      varchar(100) not null,
    created_at         timestamp with time zone not null,
    updated_at         timestamp with time zone null,
    primary key (user_id)
);

INSERT INTO public.users (user_id, first_name, last_name, email_address, created_at, updated_at) VALUES ('9f9349a6-19ce-46fe-a0cf-b4bffaba8772', 'navid', 'babakhani', 'a@f.com', '2023-01-27 18:00:59.019351 +00:00', '2023-01-27 18:00:59.019351 +00:00');

CREATE TABLE recipes
(
    id                 bigint generated by default as identity primary key,
    title              varchar(255),
    instruction        text,
    number_of_servings integer not null,
    time_to_prepare    integer null,
    user_id            uuid,
    created_at         timestamp with time zone not null,
    updated_at         timestamp with time zone null
);

CREATE TABLE ingredients
(
    id                 bigint generated by default as identity primary key,
    recipe_id          bigint references recipes(id),
    name               varchar(255),
    amount             varchar(255)
);

CREATE TABLE recipes_diets
(
    id                 bigint generated by default as identity primary key,
    recipe_id          bigint references recipes(id),
    name               varchar(50)
);